### ISSUE TITLE
Some questions and possible bugs

### ISSUE THREAD

**Issue by hmonsivais12** [schorschinho/osprey#129]
Dear Dr. Oeltzschner and al.,

I am fairly new to MRS, but your software has been of great help for me lately as I started processing data for one of my graduate projects. So far I have worked with Siemens TWIX, DICOM and RDA file formats. Everything has worked very nicely (especially for TWIX data) and I look forward to continue using your software. Below is a list of questions I have, and possible bugs that I have encountered - I'm not sure if this is the best forum for this, so if I need to post somewhere else please do let me know.  

1. I noticed that after the latest update, the 'Processed' tab in the GUI is grayed out when loading a MRSCont.mat file. 
2. When saving pdfs of the 'Cor/Seg' tab, the voxel and voxel fraction information does not show up in the pdf. Will this information show if this specific module is plotted independently? Does it need to be saved as a png or jpeg instead? 
3. I used the generated RDA files for fitting and quantification with LCModel and noticed that a lot of the header information is missing, i.e., patient id, sequence description, etc.. This doesn't interfere with the fitting or quantification, but some of title information has to be entered manually. 
4. I tried using the LCModel control files in the output folder and kept getting errors. Is there something I need to change within the control file? Like the paths? 
5. Lastly, is there a feature to import existing LCModel basis sets into Osprey format? I would like to compare some of the fitting and quantification results using Osprey and LCModel for the sLASER sequence. 

Thank you and I appreciate any answer you could provide. 

-Humberto M.

**Comment by hezoe100** [comment]
Dear Humberto,

Thank you for your positive feedback and your suggestions. It's much appreciated. Could you repost your issues on the https://mrshub.org/ forum, as inquiries 3 to 5 may be of interest to a broader audience.

1. Can you describe exactly when this is happening. Currently, if you are loading a MRScont.mat file it should be loaded into the GUI and all the modules should which were ran in the previous analysis should automatically be loaded. If you have already loaded and processed your data, these steps will be grayed out in the GUI. If you have added new files into your jobFile.m (You have to attach them to the end of the list) the relevant modules should not be grayed out and you should be able to run them for the new files.

2. This was a known bug, which was fixed in the most recent update in the develop branch.

3. All output files created with Osprey are de-identified on purpose. If you are following the recommendations of the Brain Imaging Data Structure initiative you should be able to identify your data by its filename.

4. This is currently not well documented, but will be described in the next documentation. Here is a short description on how to make this work:

In addition to the `.RAW` files, Osprey also creates the corresponding  `.CONTROL` files. These files can be used for LCModel batch processing.

```
for file in /storage/LCModelControlFiles/*;
do /usr/local/.lcmodel/bin/lcmodel < $file;
done 

```
To create working `.CONTROL` files you have to specify the following mandatory variables in the `osp_lcmcontrol_params()` function located in the process folder: `key`, `FILBAS`, `FOLDER`, and `DOECC`. 
    
```
key = 0; %Your LCM key goes here
FILBAS = '/storage/myBasisSet_30ms_PRESS.BASIS'; % Location of .BASIS file used in LCModel
FOLDER = '/storage/LCMoutput'; %Output folder (Create this on your linux machine first)
DOECC= 'F'; % No eddy current correction in LCModel as this is already performed in Osprey.
```
    
 The other parameters are optional and are described in the `osp_lcmcontrol_params()` function.

5. The `io_LCMBasis()` function in the libraries/FID-A/inputOutput folder may be useful for you. It is tested on our .BASIS files. If you have troubles during the process please let us know, as we may need to make some more adaptions on this function. In addition, you may be willing to share your .BASIS file on MRSHub.com (there is a specific folder for basis sets), as this could be useful for other users. 

Thanks again for your feedback and please report any other bugs and ideas back to us.

Helge

**Comment by hmonsivais12** [comment]
Dear Helge,

Thank you so much for your quick reply!

I will repost these questions to the MRS Hub and explain better what I meant for 1. 

I will also try 4-5 to see if I can make it work. 

Thanks again!
-Humberto

**Comment by hezoe100** [comment]
LCModel and FID-A basis set import is described in the documentation now.
