### ISSUE TITLE
[BUG] - osp_plotModule crashes in headless mode - osp_plotModule - Alex Craven

### ISSUE THREAD

**Issue by alexcraven** [schorschinho/osprey#467]
**Describe the bug**

When running Osprey without a graphical interface (eg, as part of a command line batch), the osp_plotModule crashes at the final PDF output stage.

**To Reproduce**
1. Invoke matlab from linux command line, with user interface disabled: `matlab -nodisplay` or `env -u DISPLAY matlab`
2. Usual steps to load/prepare data...
3. OspreyFit

**This happens:**

Everything works perfectly well, until `osp_plotModule`:

```
Error using validate (line 166)
Printing of uicontrols is not supported on this platform.

Error in print (line 67)
pj = validate( pj );

Error in saveas (line 181)
        print( h, name, ['-d' dev{i}] )

Error in osp_plotModule (line 621)
saveas(out,fullfile(outputFolder,outputFile),'pdf');
```

**Computer configuration**
 - OS: Linux
 - Version: Debian 11-ish (mixed)
 - MATLAB version 2019a

**Quick Workaround**

Exporting with [saveas('-noui')](https://se.mathworks.com/help/matlab/ref/print.html#d123e1146812) will work around this problem, **but** certain elements disappear: most significantly, the concentration estimates.

So the following is a partial workaround, not a complete solution: it will allow the process to run to completion, and will allow quick visual inspection of the outcomes (which for my purposes is all that is needed), but numeric info will be missing from the output.

At the bottom of osp_plotModule.m, conditionally do this instead of the standard saveas call:

```
  if osp_platform('desktop')
    saveas(out,fullfile(outputFolder,outputFile),'pdf');
  else
   print('-noui',out,fullfile(outputFolder,outputFile),'-dpdf')
  end 
```

Strictly it would be more correct to check `usejava('awt')`, since it's possible have the AWT user interface functionality without the matlab desktop environment (eg, `matlab -nodesktop`)...

I'll propose a more complete solution at a later stage; for now my batch is running so I'm happy...

**Comment by HJZollner** [comment]
Hi @alexcraven,

thanks for the report! 

We haven't tested extensively on Linux or as command line only tool. However, we have been working on a compiled version in the background which has been successfully used on a linux based server. I'll get in touch with you as soon as this feature makes into the main version.

You could also try using [MRSCont] = OspreyHTMLReport(MRSCont,kk) within your script to generate figures for QA instead of the plotPDF flag. This is also the output we are using for the linux based server integration.

Best,
Helge
